<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\CacheModelTrait;

class SiswaInfo extends Model {

    use CacheModelTrait;
    
    public $table = 'siswa_info';
    protected $primaryKey = 'siswa_id';
    protected $fillable = [
        'siswa_id', 
        'tempat_lahir', 
        'tanggal_lahir', 
        'kelamin', 
        'agama', 
        'status_keluarga', 
        'anak_ke', 
        'jml_saudara_kandung', 
        'jml_saudara_tiri', 
        'jml_saudara_angkat', 
        'yatim', 
        'kewarganegaraan', 
        'bahasa', 
        'alamat', 
        'kelurahan', 
        'kecamatan', 
        'kota', 
        'kode_pos', 
        'telp', 
        'tinggal_dengan', 
        'jarak_sekolah', 
        'golongan_darah', 
        'penyakit', 
        'kelainan', 
        'tinggi', 
        'berat', 
        'lulus_dari', 
        'no_ijazah_sebelum', 
        'tanggal_ijazah_sebelum', 
        'no_shus_sebelum', 
        'tanggal_shus_sebelum', 
        'sekolah_asal', 
        'keterangan_lain', 
        'di_kelas', 
        'tanggal_diterima', 
        'nama_ayah', 
        'tempat_lahir_ayah', 
        'tanggal_lahir_ayah', 
        'agama_ayah', 
        'kewarganegaraan_ayah', 
        'pendidikan_ayah', 
        'pekerjaan_ayah', 
        'penghasilan_ayah', 
        'telp_ayah', 
        'is_hidup_ayah', 
        'tahun_meninggal_ayah', 
        'nik_ayah', 
        'nama_ibu', 
        'tempat_lahir_ibu', 
        'tanggal_lahir_ibu', 
        'agama_ibu', 
        'kewarganegaraan_ibu', 
        'pendidikan_ibu', 
        'pekerjaan_ibu', 
        'penghasilan_ibu', 
        'telp_ibu', 
        'is_hidup_ibu', 
        'tahun_meninggal_ibu', 
        'nik_ibu', 
        'nama_wali', 
        'tempat_lahir_wali', 
        'tanggal_lahir_wali', 
        'agama_wali', 
        'kewarganegaraan_wali', 
        'pendidikan_wali', 
        'pekerjaan_wali', 
        'penghasilan_wali', 
        'telp_wali', 
        'is_hidup_wali', 
        'tahun_meninggal_wali', 
        'nik_wali', 
        'kesenian', 
        'olah_raga', 
        'organisasi', 
        'kegemaran_lain', 
        'tahun_beasiswa', 
        'tanggal_pindah', 
        'alasan_pindah', 
        'no_ijazah', 
        'tanggal_ijazah', 
        'no_shun', 
        'tanggal_shun', 
        'melanjutkan_ke', 
        'tanggal_mulai_kerja', 
        'nama_perusahaan', 
        'penghasilan', 
        'lain_lain'
    ];

}
